### ISSUE TITLE
System.IO.IOException thrown when node is in flow control for a period of time

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-dotnet-client#108]
From rabbitmq/rabbitmq-server#156:

```
I split out handling of System.IO.IOExceptionto (just print a message) from System.Exception.  I am also getting a System.ObjectDisposedException {"Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'."} with this call stack:

at System.Net.Sockets.Socket.Poll(Int32 microSeconds, SelectMode mode)
at RabbitMQ.Client.Impl.SocketFrameHandler.WriteFrameSet(IList`1 frames)
 at RabbitMQ.Client.Framing.Impl.Connection.WriteFrameSet(IList`1 f)
at RabbitMQ.Client.Impl.Command.TransmitAsFrameSet(Int32 channelNumber, Connection connection)
at RabbitMQ.Client.Impl.Command.Transmit(Int32 channelNumber, Connection connection)
at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
at RabbitMQ.Client.Framing.Impl.Model._Private_BasicPublish(String exchange, String routingKey, Boolean mandatory, Boolean immediate, IBasicProperties basicProperties, Byte[] body)
at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, Boolean immediate, IBasicProperties basicProperties, Byte[] body)
 RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)
RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, IBasicProperties basicProperties, Byte[] body)
at RabbitMQ.Client.Impl.AutorecoveringModel.BasicPublish(String exchange, String routingKey, IBasicProperties basicProperties, Byte[] body)
at rabbitPublisher.rabbitPublisher.Main(String[] args) in c:\\Users\\rizzuto\\Documents\\Visual Studio 2012\\Projects\\queuing\\rabbitPublisher\\rabbitPublisher.cs:line 69

That seems like an issue.
```

**Comment by michaelklishin** [comment]
Apparently the disposed object exception above may be due to missed heartbeats while the test app was paused by debugger.

**Comment by michaelklishin** [comment]
I tend to think this is due to github.com/rabbitmq/rabbitmq-server/issues/227 and related issues that resulted in a "natural" timeout. Closing for now, would revisit if we see this with `3.5.5` and later versions in the future.
