### ISSUE TITLE
BasicGet and then BasicPublish can cause INTERNAL_ERROR from the broker

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#1211]
While working on adding quorum queue support to the NserviceBus RabbitMQ transport, we've come across a strange problem that causes an `INTERNAL_ERROR` to be thrown.

The scenario seems to be the following:
1. Have a classic queue and publish a message to it
2. Use a different channel to `BasicGet` the message
3. Delete the queue and recreate it as a quorum queue
4. Try to publish a message to the queue using the same channel that the `BasicGet` was done from

Here's a repro that demonstrates the problem:
```csharp
using RabbitMQ.Client;

var factory = new ConnectionFactory();

var arguments = new Dictionary<string, object> { { "x-queue-type", "quorum" } };
using var connection = factory.CreateConnection();

using var channel = connection.CreateModel();
channel.ConfirmSelect();

//replace all secondChannel usage with channel and the code will work properly
using var secondChannel = connection.CreateModel();
secondChannel.ConfirmSelect();

channel.QueueDeclare("main", true, false, false); //create classic queue
channel.BasicPublish(string.Empty, "main", channel.CreateBasicProperties(), ReadOnlyMemory<byte>.Empty);
channel.WaitForConfirmsOrDie();

var message = secondChannel.BasicGet("main", false);
secondChannel.BasicAck(message.DeliveryTag, false);

channel.QueueDelete("main");
channel.QueueDeclare("main", true, false, false, arguments); //create quorum queue

secondChannel.BasicPublish(string.Empty, "main", secondChannel.CreateBasicProperties(), ReadOnlyMemory<byte>.Empty);
secondChannel.WaitForConfirmsOrDie(); //throws AlreadyClosedException here

channel.QueueDelete("main");
```

This code throws the following exception:
```
RabbitMQ.Client.Exceptions.AlreadyClosedException
  HResult=0x80131500
  Message=Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=541, text='INTERNAL_ERROR', classId=0, methodId=0
  Source=RabbitMQ.Client
  StackTrace:
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirms(TimeSpan timeout, Boolean& timedOut)
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirmsOrDie(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.WaitForConfirmsOrDie()
   at RabbitMQ.Client.Impl.AutorecoveringModel.WaitForConfirmsOrDie()
   at Program.<Main>$(String[] args) in C:\Code\RabbitChannelBugRepro\Program.cs:line 28
```

The repro code is located at https://github.com/andreasohlund/RabbitChannelBugRepro if you want to try it out for yourself.

The repository also includes packet captures of the repro code running, both as-is (broken.pcapng) and with only a single channel used (works.pcapng). There is a also a server log file of when the code is run, showing the error that is logged.

Looking at the packet captures, nothing stood out to me as obviously different/wrong, so I suppose this could be a broker problem and not a client problem, but I'm not sure, so I opened the issue here first.

**Comment by michaelklishin** [comment]
Publishing and consuming from a queue that's being redeclared using a different type is very likely to introduce a race condition between things that never coordinate. I don't think it can be universally solved.

What's in the server logs?

**Comment by bording** [comment]
> What's in the server logs?

The errors start at https://github.com/andreasohlund/RabbitChannelBugRepro/blob/main/captures/rabbit%40RabbitMQ.log#L160

**Comment by lukebakken** [comment]
Thanks @bording, I'll find time to check this out. Have a good weekend.
