### ISSUE TITLE
Cancelling `ModelSendAsync` can close the connection when it shouldn't

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-dotnet-client#1750]
### Describe the bug

Reported here: https://github.com/rabbitmq/rabbitmq-dotnet-client/discussions/1720#discussioncomment-11605340

### Reproduction steps

* Pass cancellation token to `BasicConsumeAsync` that will close in the future.
* Notice that the connection is closed:
    ```
    CloseReason: AMQP close-reason, initiated by Library, code=541, text='A task was canceled.', classId=0, methodId=0, exception=System.Threading.Tasks.TaskCanceledException: A task was canceled.
    at RabbitMQ.Client.Impl.BasicConsumeAsyncRpcContinuation.HandleCommandAsync(IncomingCommand cmd)
    at RabbitMQ.Client.Impl.Channel.HandleCommandAsync(IncomingCommand cmd, CancellationToken cancellationToken)
    at RabbitMQ.Client.Framing.Connection.ProcessFrameAsync(InboundFrame frame, CancellationToken cancellationToken)
    at RabbitMQ.Client.Framing.Connection.ReceiveLoopAsync(CancellationToken mainLoopCancellationToken)
    at RabbitMQ.Client.Framing.Connection.MainLoop()
    ```

### Expected behavior

Connection should not close in this case.

### Additional context

https://github.com/rabbitmq/rabbitmq-dotnet-client/discussions/1720#discussioncomment-11605340

**Comment by PiotrZajacGV** [comment]
I think passing already cancelled cancellation token will trigger exception already on the await _rpcSemaphore.WaitAsync(k.CancellationToken). The problem occurs when it's passed to the Connection.

Any exception thrown from the `HandleCommandAsync` method of `AsyncRpcContinuation<T>` is causing closing the Connection.

**Comment by ZajacPiotr98** [comment]
I think passing already cancelled cancellation token will trigger exception already on the await _rpcSemaphore.WaitAsync(k.CancellationToken). The problem occurs when it's passed to the Connection.

Any exception thrown from the HandleCommandAsync method of AsyncRpcContinuation<T> is causing closing the Connection.

**Comment by lukebakken** [comment]
@ZajacPiotr98 if you have time to test #1753, I would appreciate it. Thanks!
