### ISSUE TITLE
Exception thrown when connecting to a queue using RabbitMQ.Client.CoreClrUnofficial 3.6.1.2-rc2 library

### ISSUE THREAD

**Issue by vishal-uttamchandani** [rabbitmq/rabbitmq-dotnet-client#222]
OS: Windows 10 Pro

The below code works fine with **RabbitMQ.Client 3.6.3** library  (**targeting .net framework 4.5.1**)

```cs

using System;
using System.Text;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
             var factory = new ConnectionFactory
            {
                HostName = "192.168.99.100",
                Port = 5678   // not using default 5672
            };

            using (var connection = factory.CreateConnection())
            {
                using (var channel = connection.CreateModel())
                {
                    var consumer = new EventingBasicConsumer(channel);
                    consumer.Received += (model, ea) =>
                    {
                        var body = ea.Body;
                        var message = Encoding.UTF8.GetString(body);
                        Console.WriteLine(" [x] Received {0}", message);
                    };
                    channel.BasicConsume(queue: "Demo", noAck: true, consumer: consumer);

                    Console.ReadLine();
                }
            }
        }
    }
}

```

Same code throws exception when using **RabbitMQ.Client.CoreClrUnofficial 3.6.1.2-rc2** library  (**targeting .net core 1.0.0**)

Unhandled Exception: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.AggregateException: One or more errors occurred. (Connection failed) ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.ArgumentException: None of the discovered or specified addresses match the socket address family.
Parameter name: context
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.BeginConnect(String host, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsyncCore>b__62_0(String targetHost, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Sockets.TcpClient.ConnectAsyncCore(String host, Int32 port)
   at System.Net.Sockets.TcpClient.ConnectAsync(String host, Int32 port)
   at RabbitMQ.Client.TcpClientAdapter.ConnectAsync(String host, Int32 port)
   at RabbitMQ.Client.Impl.SocketFrameHandler.<ConnectAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.SocketFrameHandler.<ConnectAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 connectionTimeout, Int32 readTimeout, Int32 writeTimeout)
   at RabbitMQ.Client.Framing.Impl.ProtocolBase.CreateFrameHandler(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 connectionTimeout, Int32 readTimeout, Int32 writeTimeout)
   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler()
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 hostnames, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 hostnames, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection()
   at ConsoleApplication.Program.Main(String[] args)

**Comment by michaelklishin** [comment]
`RabbitMQ.Client.CoreClrUnofficial 3.6.1.2-rc2` is not a version that we released or maintain. If you need .NET Core support, please see #148 and related announcements on the mailing list.

**Comment by vishal-uttamchandani** [comment]
@michaelklishin Thanks. Client library @ https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-ci worked just fine.
