### ISSUE TITLE
Timeout exception when trying to declare a queue (or exchange)

### ISSUE THREAD

**Issue by tomekpr** [rabbitmq/rabbitmq-dotnet-client#310]
hi,

I'm seeing a lot of timeout exceptions when trying to declare an exchange / or a queue. Could these exceptions be caused by the fact that we accidentally share models across many threads? So far I noticed that these problems happen only when our systems are under high load (> 80% cpu)

RMQ version 3.6.5

Error attempting to get publisher connection to declare queue my_test_queue on host localhost
System.TimeoutException: The operation has timed out.
   at RabbitMQ.Util.BlockingCell.GetValue(TimeSpan timeout) in c:\git\RabbitMQ\projects\client\RabbitMQ.Client\src\util\BlockingCell.cs:line 130
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout) in c:\git\RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\SimpleBlockingRpcContinuation.cs:line 74
   at RabbitMQ.Client.Framing.Impl.Model._Private_QueueDelete(String queue, Boolean ifUnused, Boolean ifEmpty, Boolean nowait) in c:\git\RabbitMQ\gensrc\RabbitMQ.Client\autogenerated-api-0-9-1.cs:line 4120
   at RabbitMQ.Client.Impl.AutorecoveringModel.QueueDelete(String queue, Boolean ifUnused, Boolean ifEmpty) in c:\git\RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\AutorecoveringModel.cs:line 1123
   

Above exceptions also cause another error. Stack trace below:

Error attempting to declare exchange EX on host localhost
System.NotSupportedException: Pipelining of requests forbidden
   at RabbitMQ.Client.Impl.RpcContinuationQueue.Enqueue(IRpcContinuation k) in RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\RpcContinuationQueue.cs:line 79
   at RabbitMQ.Client.Impl.ModelBase.Enqueue(IRpcContinuation k) in RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\ModelBase.cs:line 415
   at RabbitMQ.Client.Framing.Impl.Model._Private_ExchangeDeclare(String exchange, String type, Boolean passive, Boolean durable, Boolean autoDelete, Boolean internal, Boolean nowait, IDictionary`2 arguments) in RabbitMQ\gensrc\RabbitMQ.Client\autogenerated-api-0-9-1.cs:line 4016
   at RabbitMQ.Client.Impl.AutorecoveringModel.ExchangeDeclare(String exchange, String type, Boolean durable, Boolean autoDelete, IDictionary`2 arguments) in RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\AutorecoveringModel.cs:line 967

The 'pipelining of requests forbidden' is caused by the fact that there is an internal 'queue' which allows only one element. Unfortunately
existing element doesn't get consumed from the queue and is stuck there forever leading to a situation where nothing else can be done with that queue.
We had to run a CLI command on rabbitmq server to get rid of that queue.

I don't have a unit test case yet to reproduce this problem but I'm hoping that someone can shed light on it or point towards better explanation of this issue.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Timeouts are a fact of life in distributed and concurrent systems, in particular under load. In some other clients continuation timeout is a configurable value. There is no other way to avoid them.

**Comment by michaelklishin** [comment]
Actually, there is another option: synchronous protocol operations such as `queue.declare` provide a `nowait` option that makes the server not send a response. It doesn't make any sense with server-named queues but *could* be an option for some applications that use client-named queues. I would not recommend it for most cases, however.

**Comment by michaelklishin** [comment]
Some digging suggests [continuation timeouts are configurable](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/bfaee6ccb60a557fe0d38ce668338ccec95945ae/projects/client/RabbitMQ.Client/src/client/impl/ModelBase.cs#L67) ([in IModel](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/bfaee6ccb60a557fe0d38ce668338ccec95945ae/projects/client/RabbitMQ.Client/src/client/api/IModel.cs#L510)), as of https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/93cdd66867c92cb281f01243d4b278c09f3c87bd.

**Comment by tomekpr** [comment]
Thanks. I just checked graphs again and it looks that first occurrence of this problem happened when CPU usage on my VM host was around 60-70%. CPU on server was ok.

**Comment by michaelklishin** [comment]
…and, of course, with [alarms](http://www.rabbitmq.com/alarms.html) in effect timeouts are extremely likely so see your server's logs.

**Comment by stevenxi** [comment]
@michaelklishin  We had similar issue. And the point is not in fact about the timeout.
It's about the *System.NotSupportedException: Pipelining of requests forbidden*
Once there's a timeout happened, all following operation will result "Pipelining of requests forbidden" error. And I doubt it's caused by simultaneously call.

Would you please re-open this issue? Or I should create another issue for the "Pipelining of requests forbidden" exception?

Thanks.

**Comment by michaelklishin** [comment]
@stevenxi this is mailing list material. When a continuation times out it can be a natural consequence that more operations are attempted by application code immediately after. This is something we've seen in at least two other clients with a similar architecture.

 Without a way to reproduce we cannot suggest much. New issues with the same amount of information will be closed and redirected to the mailing list.
