### ISSUE TITLE
Calling ExchangeBind more than once with the same arguments is throwing

### ISSUE THREAD

**Issue by bording** [rabbitmq/rabbitmq-dotnet-client#314]
While testing https://github.com/Particular/NServiceBus.RabbitMQ against `5.0.0-pre3`, I've come across a problem. 

Here's a repro:

```csharp
var factory = new ConnectionFactory();
var connection = factory.CreateConnection();
var channel = connection.CreateModel();

channel.ExchangeDeclare("test1", ExchangeType.Fanout);
channel.ExchangeDeclare("test2", ExchangeType.Fanout);

channel.ExchangeBind("test1", "test2", "");
channel.ExchangeBind("test1", "test2", ""); //this throws
```

The second `ExchangeBind` throws the following exception:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=The key already existed in the dictionary.
  Source=mscorlib
  StackTrace:
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.RecordBinding(RecordedBinding rb)
   at RabbitMQ.Client.Impl.AutorecoveringModel.ExchangeBind(String destination, String source, String routingKey, IDictionary`2 arguments)
   at RabbitMQ.Client.IModelExensions.ExchangeBind(IModel model, String destination, String source, String routingKey, IDictionary`2 arguments)
   at ConsoleApp1.Program.Main(String[] args) in c:\users\brandon\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 24
```

Looks like this repros on both `5.0.0-pre2` and `5.0.0-pre3`, but <= `4.1.1` works correctly.

**Comment by kjnilsson** [comment]
Thanks. Sounds like a regression.

**Comment by michaelklishin** [comment]
@bording but it's not present in earlier versions, correct?

**Comment by bording** [comment]
@michaelklishin Correct. I tested it on 4.1.1, 3.6.6 and 3.6.7 and they are all fine. All previous versions should be fine as well since this is a common pattern in our code and we've never seen this problem before.

**Comment by adamralph** [comment]
👍 great. FYI, we'll test the next 5.0.0 pre-release with NServiceBus.RabbitMQ as soon as you publish it to NuGet.

**Comment by kjnilsson** [comment]
@adamralph pre4 is [out](https://www.nuget.org/packages/RabbitMQ.Client/5.0.0-pre4)

**Comment by adamralph** [comment]
@kjnilsson thanks. FYI we just had [a green build with pre4](https://github.com/Particular/NServiceBus.RabbitMQ/pull/354) so we can confirm that this regression is fixed from our POV.

**Comment by kjnilsson** [comment]
Good to hear. Thanks for reporting back.
