### ISSUE TITLE
Should the client skip channels that fail to recover and continue?

### ISSUE THREAD

**Issue by Mattish** [rabbitmq/rabbitmq-dotnet-client#318]
`AutorecoveringConnection.m_models` is a list of model to recover. During `RecoverModels` if any model recovery fails, it will not try anymore in the list. Leaving the Connection recovered, but models which are still in a closed/faulted state.

This means that a `Model` could remain permanently closed, unless another connection recovery occurs and it tries this `Model` recovery again. In turn, in my own code I must check if a `Model` is closed and `Dispose()` and recreate it myself to get a new `Model` as I have no guarantee it will be 'automatically' restored.

What this means in reality is I have no way of knowing if a `Model` 'wasn't recovered'(without some very guess work-y checking of fields) so I *must* destroy any `Model` which is closed and attempt to recreate myself.

Am I missing something here? Should I be somehow attempting to work out these broken `Model` and calling some function to force an attempt at recovering it? Either way currently I am having to write my own Model 'recovery'.

Version: master

**Comment by Mattish** [comment]
Example stack trace of a throw:

```
System.TimeoutException: The operation has timed out.
   at RabbitMQ.Util.BlockingCell.GetValue(TimeSpan timeout) in ...\RabbitMQ\projects\client\RabbitMQ.Client\src\util\BlockingCell.cs:line 127
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout) in ...\RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\SimpleBlockingRpcContinuation.cs:line 74
   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(String outOfBand) in ...\RabbitMQ\gensrc\RabbitMQ.Client\autogenerated-api-0-9-1.cs:line 3907
   at RabbitMQ.Client.Impl.AutorecoveringModel.AutomaticallyRecover(AutorecoveringConnection conn, IConnection connDelegate) in ...\RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\AutorecoveringModel.cs:line 272
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.RecoverModels() in ...\RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\AutorecoveringConnection.cs:line 1012
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.PerformAutomaticRecovery() in ...\RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\AutorecoveringConnection.cs:line 424
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.<>c__DisplayClass90_0.<BeginAutomaticRecovery>b__0() in ...\RabbitMQ\projects\client\RabbitMQ.Client\src\client\impl\AutorecoveringConnection.cs:line 392
```

**Comment by michaelklishin** [comment]
Recovery operations are not guaranteed to succeed. The best client libraries can do (and I think at least Bunny does?) is to log an error and proceed but it's an open ended question whether the recovery then should be considered a success.

I'm not sure how you'd "call a function to fix a timeout."

You do have a way of knowing if a model was recovered: just check that it is open. That works very well in practice.

**Comment by michaelklishin** [comment]
I'm leaving this open even though it's a discussion because the subject and the options are already clear enough. No need to move it to the mailing list.

**Comment by Mattish** [comment]
> You do have a way of knowing if a model was recovered: just check that it is open. That works very well in practice.

If a connection recovery process throws at all during model recovery, then a recovery event is not raised. I have no information about the state of the recovery process or that it has finished. 

I just want to make sure that based on this; If attempt to use a Channel in any means, but its Closed, then I should always dispose and create a new channel irregardless of my recovery settings?

**Comment by michaelklishin** [comment]
@Mattish yes, channels are disposable material. There is no way to "reuse" a closed channel anyway, automatic channel recovery simply reuses channel IDs to make things more predictable for those (misinformed) folks who rely on channel ID for anything.

**Comment by michaelklishin** [comment]
Closed the wrong issue. This is worth some consideration.

**Comment by michaelklishin** [comment]
After a couple of months I'm not convinced this is a good idea.
