### ISSUE TITLE
The remote certificate is invalid according to the validation procedure when using AWS ELB Certificate.

### ISSUE THREAD

**Issue by jghankins** [rabbitmq/rabbitmq-dotnet-client#366]
When using 5.01 version of .NET Client Against Server RabbitMQ Server 3.6.12 / Erlang 20.1.2 behind an Amazon Web Services ELB with TLS offload configuration (SSL 5171 >> TCP 5172) getting an exception: (Below)  Certificate is ACM Based and predefined security policy: ElbSecurityPolicy2016-08

Work around was to add:

factory.Ssl.AcceptablePolicyErrors = SslPolicyErrors.RemoteCertificateNameMismatch;

Even though there was not a hostname mismatch. between the provided hostname to the connection factory and the certificate.

This only affects the .NET clients, our Java clients have no issue using same ELB/Rabbit combination.  

Rabbit Cluster with 3 Nodes with an External and Internal Elastic Load balancer using Classic ELB.

RabbitMQ.Client.Exceptions.BrokerUnreachableException was unhandled
  HResult=-2146232800
  Message=None of the specified endpoints were reachable
  Source=RabbitMQ.Client
  StackTrace:
       at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
       at RabbitMQ.Client.ConnectionFactory.CreateConnection()
       at RabbitMQTest.CommsTesting.button1_Click(Object sender, EventArgs e) in C:\Users\jim\OneDrive\Documents\Visual Studio 2015\Projects\RabbitMQTest\RabbitMQTest\CommsTesting.cs:line 50
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at RabbitMQTest.Program.Main() in C:\Users\jim\OneDrive\Documents\Visual Studio 2015\Projects\RabbitMQTest\RabbitMQTest\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233087
       Message=The remote certificate is invalid according to the validation procedure.
       Source=RabbitMQ.Client
       StackTrace:
            at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
            at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
            at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
       InnerException:

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest anything with this amount of information.

JVM and .NET use different certificate formats, trust store management procedures, possibly defaults, and so on. There is a [generic TLS troubleshooting guide](http://www.rabbitmq.com/troubleshooting-ssl.html) that can help narrow the issue down.

99% of TLS related issues are environment-specific.

**Comment by lukebakken** [comment]
@jghankins - be sure to use the DNS-resolvable host name for the ELB as the `serverName` parameter [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/SslOption.cs#L65). Also, the `CN=` value in the server certificate must match the DNS-resolvable host name.

We're happy to continue assistance on the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users).
