### ISSUE TITLE
Autorecovery does not recover consumers when topology recovery is disabled

### ISSUE THREAD

**Issue by dbuchko** [rabbitmq/rabbitmq-dotnet-client#383]
When `autorecovery` is enabled, and `topologyrecovery` is disabled, consumers do not resume message consumption from queues after being disconnected from the server.  In the `PerformAutomaticRecovery()` method of the `AutorecoveringConnection.cs`, the `RecoverConsumers()` method is only invoked if topology recovery is enabled.  The `RecoverConsumers()` method should be invoked regardless of whether topology recovery is enabled.  i.e. current code is:

```
        protected void PerformAutomaticRecovery()
        {
            ESLog.Info("Performing automatic recovery");
            lock (recoveryLockTarget)
            {
                if (RecoverConnectionDelegate())
                {
                    RecoverConnectionShutdownHandlers();
                    RecoverConnectionBlockedHandlers();
                    RecoverConnectionUnblockedHandlers();

                    RecoverModels();
                    if (m_factory.TopologyRecoveryEnabled)
                    {
                        RecoverEntities();
                        RecoverConsumers();
                    }

                    ESLog.Info("Connection recovery completed");
                    RunRecoveryEventHandlers();
                }
                else
                {
                    ESLog.Warn("Connection delegate was manually closed. Aborted recovery.");
                }
            }
        }
```

I believe it should be:
```
        protected void PerformAutomaticRecovery()
        {
            ESLog.Info("Performing automatic recovery");
            lock (recoveryLockTarget)
            {
                if (RecoverConnectionDelegate())
                {
                    RecoverConnectionShutdownHandlers();
                    RecoverConnectionBlockedHandlers();
                    RecoverConnectionUnblockedHandlers();

                    RecoverModels();
                    if (m_factory.TopologyRecoveryEnabled)
                    {
                        RecoverEntities();
                    }

                    RecoverConsumers();
                    ESLog.Info("Connection recovery completed");
                    RunRecoveryEventHandlers();
                }
                else
                {
                    ESLog.Warn("Connection delegate was manually closed. Aborted recovery.");
                }
            }
        }
```

.NET client version 5.0.1
Tested on:
- RabbitMQ version 3.6.1, Erlang 17.5
- RabbitMQ version 3.6.14, Erlang 19.3.6.4

Sample publisher:  https://github.com/dbuchko/Publisher/tree/autorecover-issue
Sample listener:  https://github.com/dbuchko/Listener/tree/autorecover-issue

To reproduce the issue:

1. Start up a local RabbitMQ server instance
```
rabbitmq_server-3.6.1 $sbin/rabbitmq-server 

              RabbitMQ 3.6.1. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /Users/danielbuchko/apps/rabbitmq/rabbitmq_server-3.6.1/var/log/rabbitmq/rabbit@Dans-MacBook-Pro-2.log
  ######  ##        /Users/danielbuchko/apps/rabbitmq/rabbitmq_server-3.6.1/var/log/rabbitmq/rabbit@Dans-MacBook-Pro-2-sasl.log
  ##########
              Starting broker... completed with 7 plugins.
```

2. Check out the sample listener.
```
$git clone https://github.com/dbuchko/Listener
Cloning into 'Listener'...
remote: Counting objects: 46, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 46 (delta 4), reused 8 (delta 2), pack-reused 35
Unpacking objects: 100% (46/46), done.
$cd Listener/
Listener $git checkout tags/autorecover-issue
Note: checking out 'tags/autorecover-issue'.
...
HEAD is now at a51beae... Added conditional code for running locally or on PCF.
```
3. Build the sample Listener.
```
Listener $dotnet build
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Listener -> /Users/danielbuchko/tmp/Listener/bin/Debug/netcoreapp2.0/Listener.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.03
```

4. Start the Listener.
```
Listener $dotnet run
HEARTBEAT_INTERVAL_SEC environment variable not defined, using default.
Setting heartbeat interval to 20 s
 [*] Waiting for messages.
```

5. In another terminal window, check out the sample Publisher.  
```
$git clone https://github.com/dbuchko/Publisher
Cloning into 'Publisher'...
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 34 (delta 2), reused 7 (delta 2), pack-reused 26
Unpacking objects: 100% (34/34), done.
tmp $cd Publisher/
Publisher $git checkout tags/autorecover-issue
Note: checking out 'tags/autorecover-issue'.

You are in 'detached HEAD' state. You can look around, make experimental
...
HEAD is now at 06233ef... Added conditional code for running locally or on PCF.
```
6. Build the sample Publisher.
```
Publisher $dotnet build
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Publisher -> /Users/danielbuchko/tmp/Publisher/bin/Debug/netcoreapp2.0/Publisher.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.82
Publisher $
```

7. Set the `PUBLISH_INTERVAL_SEC` environment variable to a reasonable value, eg. `5` to publish a message every 5 seconds, and run the Publisher.
```
Publisher $PUBLISH_INTERVAL_SEC=5 dotnet run
HEARTBEAT_INTERVAL_SEC environment variable not defined, using default.
Setting heartbeat interval to 20 s
Message publish interval is 5 s
Published 1 messages
Published 2 messages
Published 3 messages
```

8. Observe the listener consuming messages
```
Listener $dotnet run
HEARTBEAT_INTERVAL_SEC environment variable not defined, using default.
Setting heartbeat interval to 20 s
 [*] Waiting for messages.
Received 1 messages
Received 2 messages
Received 3 messages
```

7. Kill the RabbitMQ server instance.  The Publisher process will die, but the Listener will go into recovery mode and try to reconnect:
```
Channel closed: 
*** Entering Shutdown ***
Error: Connection didn't close cleanly. Socket closed unexpectedly
Error: Exception: System.IO.IOException
Unable to read data from the transport connection: Connection reset by peer.

   at RabbitMQ.Client.Impl.Frame.ReadFrom(NetworkBinaryReader reader)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.ClosingLoop()
InnerException:
System.Net.Sockets.SocketException (0x80004005): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
Informational: Performing automatic recovery
Error: Connection recovery exception.
Error: Exception: RabbitMQ.Client.Exceptions.ConnectFailureException
Connection failed

   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.RecoverConnectionDelegate()
InnerException:
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Connection refused 127.0.0.1:5672
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
Error: Connection recovery exception.
Error: Exception: RabbitMQ.Client.Exceptions.ConnectFailureException
Connection failed

   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.RecoverConnectionDelegate()
InnerException:
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Connection refused 127.0.0.1:5672
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
Error: Connection recovery exception.
Error: Exception: RabbitMQ.Client.Exceptions.ConnectFailureException
Connection failed
```
8. Restart the RabbitMQ server.

9. Observe the output from the Listener, that recovery has completed:
```
Error: Connection recovery exception.
Error: Exception: RabbitMQ.Client.Exceptions.ConnectFailureException
Connection failed

   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.RecoverConnectionDelegate()
InnerException:
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (0x80004005): Connection refused 127.0.0.1:5672
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
Informational: Connection recovery completed
```
10.  Restart the Publisher.
```
Publisher $PUBLISH_INTERVAL_SEC=5 dotnet run
HEARTBEAT_INTERVAL_SEC environment variable not defined, using default.
Setting heartbeat interval to 20 s
Message publish interval is 5 s
Published 1 messages
Published 2 messages
```
11.  Observe that the Listener does not resume consuming messages.
```
...
Informational: Connection recovery completed
```

**Comment by michaelklishin** [comment]
Consumer recovery is a part of topology recovery by design.

**Comment by bording** [comment]
@dbuchko I suspect the reason this isn't currently done is because of all the various features that RabbitMQ supports that can make queues temporary (durability, exclusive queues, TTLs, auto-delete queues).

If you've skipped topology recovery, then there is no guarantee the queue exists once the connection is reestablished, so attempting to recover the consumers could fail.

**Comment by michaelklishin** [comment]
@bording is correct but there is another reason. Connection recovery was first introduced in a couple of Ruby clients that use objects for queues. Back then there was no way to register a consumer without obtaining a queue reference one way or another (today there is but very few users do that).
The overall algorithm worked so well that we ported it to other clients as is, and this means consumer recovery is one of the last steps.

I don’t think recovering consumers without recovering the topology is a good idea. Those who believe it is can recover consumers manually.
