### ISSUE TITLE
Override parameterless constructor in consumer class

### ISSUE THREAD

**Issue by eramosr18** [rabbitmq/rabbitmq-dotnet-client#458]
Hi, I'm trying to inject some services to some of the consumer class as you can see here:

```
public class SiteCreatedHandler : IConsume<SiteCreated>
    {
        private readonly ILogger _log;
        private readonly IBus _bus;

   
        public SiteCreatedHandler(IBus bus, ILogger log)
        {
            _bus = bus;
            _log = log;
        }
```

When I push a message to the queue I'm having an error like this:

**OCCURRED:System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance[T]()
   at EasyNetQ.AutoSubscribe.DefaultAutoSubscriberMessageDispatcher.Dispatch[TMessage,TConsumer](TMessage message)
   at EasyNetQ.Internals.TaskHelpers.ExecuteSynchronously(Action action)
--- End of stack trace from previous location where exception was thrown ---
   at EasyNetQ.Consumer.HandlerRunner.InvokeUserMessageHandlerInternalAsync(ConsumerExecutionContext context)**

Is there a way I can override this behavior and get the instance using IOC or DI??.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by eramosr18** [comment]
Sorry @michaelklishin  I wasn't sure where to put it. Have a good day!!.
