### ISSUE TITLE
Unhandled Exception: System.IO.FileLoadException

### ISSUE THREAD

**Issue by linhdh** [rabbitmq/rabbitmq-dotnet-client#461]
I use RabbitMQ for .net version 5.0.0. Some time my program crash because of following exception:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at RabbitMQ.Client.ESLog.Error(String message, Exception ex)
   at RabbitMQ.Client.Framing.Impl.Connection.LogCloseError(String error, Exception ex)
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I need your help to solve this issue to stabilize my server.
thank you in advance.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This has been discussed on the mailing list [before](https://groups.google.com/d/msg/rabbitmq-users/vqXM0B0m48U/LeFMN4NYAgAJ) as well as filed here multiple times with [similar results](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/420#issuecomment-404938726).

The dependency has been removed for 6.0.
