### ISSUE TITLE
AlreadyClosedException vhost is down

### ISSUE THREAD

**Issue by eugenerud** [rabbitmq/rabbitmq-dotnet-client#496]
Hello guys.

From time to time (especially during heavy load of Rabbit) I am encountering the following exception from RabbitMQ.Net client:

ERROR RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=320, text="CONNECTION_FORCED - vhost 'UAT' is down", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Impl.RecoveryAwareModel.BasicAck(UInt64 deliveryTag, Boolean multiple)
   at RabbitMQ.Client.Impl.AutorecoveringModel.BasicAck(UInt64 deliveryTag, Boolean multiple)

Could you please suggest why it happens and how handle it properly or how to avoid it.

Thank you in advance.

**Comment by michaelklishin** [comment]
I think the answer is more or less obvious: if a virtual host is down RabbitMQ cannot accept any connections on it. Depending on the scenarios listed above it may or may not be a temporary condition. Again, this lacks any information from the logs and is mailing list material.
