### ISSUE TITLE
RabbitMQ randomly disconnects from server on localhost

### ISSUE THREAD

**Issue by scratch-net** [rabbitmq/rabbitmq-dotnet-client#77]
I use RabbitMQ 3.5.1 and latest .net client.
I often get
System.IO.EndOfStreamException: SharedQueue closed
   at RabbitMQ.Util.SharedQueue`1.EnsureIsOpen()
   at RabbitMQ.Util.SharedQueue`1.Dequeue(Int32 millisecondsTimeout, T& result)

though both client and server reside on the same host & heartbeat is enabled 

An example of a program that receives such errors is:
```
 static void InternalTask()
  {
   var factory = new ConnectionFactory() { HostName = "localhost",RequestedHeartbeat = 30};
   using (var connection = factory.CreateConnection())
   {
    using (var channel = connection.CreateModel())
    {
     channel.QueueDeclare("LoneWorker", true, false, false, null);

     channel.BasicQos(0, 1, false);
     var consumer = new QueueingBasicConsumer(channel);
     channel.BasicConsume("LoneWorker", false, consumer);
     _loger.Info(" [*] Waiting for messages.  To exit press CTRL+C");
     while (true)
     {
      var ea =consumer.Queue.Dequeue();

      var body = ea.Body;
      var message = Encoding.UTF8.GetString(body);
      _loger.Info(" [x] Received {0}", message);
      channel.BasicAck(ea.DeliveryTag, false);
     }
    }
   }
  }
```

**Comment by michaelklishin** [comment]
#68, #71.
