### ISSUE TITLE
TimeOut During RabbitMQ.Util.BlockingCell.GetValue

### ISSUE THREAD

**Issue by esraince1** [rabbitmq/rabbitmq-dotnet-client#785]
Hello  ,
We have 3 rabbitmq Nodes in our production environment. During a minute, error below in our error trace logs observed.
Can anyone help with the reason ?  We use version 3.7.7 on server side and erlang 10.0.1 ,  and  4.0.0 in client side. Autorecovery mode is set to true at connection factory.

ERROR 1 : System.TimeoutException: The operation has timed out.

   at RabbitMQ.Util.BlockingCell.GetValue(TimeSpan timeout)

   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)

   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)

   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(String outOfBand)

   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateNonRecoveringModel()

   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateModel()

   at System.Lazy`1.CreateValue()

   at System.Lazy`1.LazyInitValue() 

ERROR 2 : System.TimeoutException: The operation has timed out.

   at RabbitMQ.Util.BlockingCell.GetValue(TimeSpan timeout)

   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)

   at RabbitMQ.Client.Impl.ModelBase.BasicConsume(String queue, Boolean noAck, String consumerTag, Boolean noLocal, Boolean exclusive, IDictionary`2 arguments, IBasicConsumer consumer)

   at RabbitMQ.Client.Impl.AutorecoveringModel.BasicConsume(String queue, Boolean noAck, String consumerTag, Boolean noLocal, Boolean exclusive, IDictionary`2 arguments, IBasicConsumer consumer)

   at RabbitMQ.Client.IModelExensions.BasicConsume(IModel model, String queue, Boolean noAck, IBasicConsumer consumer)

   at RabbitMQClass.TryDequeue(IModel model, String queueCode, BasicDeliverEventArgs& result)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Timeouts (in this case, when opening a channel) can happen: it's a sad fact of life in distributed systems. We are not aware of any scenarios where a client would report an operation timeout as a false positive. See [server logs](https://www.rabbitmq.com/logging.html) for additional clues.

You might want to upgrade your client to 5.x since 6.0 is going to ship soon. Both do not require upgrading RabbitMQ at the same time although 3.7.7 is [17 patch releases behind](https://www.rabbitmq.com/changelog.html) in the 3.7 series alone and 3.7 [goes out of general support soon](https://www.rabbitmq.com/versions.html).

**Comment by esraince1** [comment]
Thank you for response.

Michael Klishin <notifications@github.com>, 27 Mar 2020 Cum, 16:49
tarihinde şunu yazdı:
