### ISSUE TITLE
Factory.CreateConnection() throws BrokerUnreachableException in Async context

### ISSUE THREAD

**Issue by bard83** [rabbitmq/rabbitmq-dotnet-client#791]
Hi, 

I'm encountering this problem when I try to send to rabbit a lot of messages in an Async context. The `ConnectionFactory` seems to have trouble in such situation. Time to time it throws exception, below the stack trace. 

I've created this [repo](https://github.com/bard83/TestRabbitClient) that reproduces the problem.

My expectation is to delivery without any problems all the messages to RabbitMQ. In my example circa the ~80% of the messages are delivered.

May it be related to the following issues?
- [403](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/403)
- [256](https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/256)

```
Error occurred : RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> System.AggregateException: One or more errors occurred. (Connection failed)
 ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed
 ---> System.TimeoutException: The operation has timed out.
   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection()
   at TestRabbitClient.Channel.RbConnectionFactoryWrapper.CreateConnection() in /app/Channel/RbConnectionFactoryWrapper.cs:line 32
   at TestRabbitClient.Channel.RabbitMqChannel.Publish(String message) in /app/Channel/RabbitMqChannel.cs:line 66
   at TestRabbitClient.Channel.RabbitMqChannel.<>c__DisplayClass4_0.<PublishAsync>g__Impl|0() in /app/Channel/RabbitMqChannel.cs:line 50
```

Thanks in advance

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by lukebakken** [comment]
Your tests open a [connection-per-message](https://github.com/bard83/TestRabbitClient/blob/master/Channel/RabbitMqChannel.cs#L60-L83). This is literally the least efficient way you can use RabbitMQ and I suspect is the cause of what you are seeing.

**Comment by michaelklishin** [comment]
Thank you for the example. Please remove all wrappers and demonstrate the behavior with as little additional code as possible. The exception says that there was a timeout, so we'd need a traffic capture and server logs.

Your code instantiates a "barrier channel" per message and the exception comes from a method that opens a TCP connection. To me this strongly suggests you may be opening a connection per message which is [wrong](https://www.rabbitmq.com/connections.html) and is expected to start timing out because [server resources are limited](https://www.rabbitmq.com/networking.html#open-file-handle-limit) in ways you probably would not expect when it comes to a flood of connections.

**Comment by michaelklishin** [comment]
Thanks for confirming my hypothesis @lukebakken. Efficiency aside, flooding a node with TCP connections is guaranteed to begin hitting timeouts after a certain rate for two reasons:

 * TCP acceptor queue (no relation to RabbitMQ queues) is usually limited to a few hundred pending connections. Once this is full, the kernel will begin rejecting new ones.
 * The file handle limit, even if significantly increased, is not limited. And it's mere 1024 on Linux by default.

So the "connection per message" strategy is guaranteed to fail with rates even in a few hundreds of messages per second.

[Connection and Channel Lifespan](https://www.rabbitmq.com/dotnet-api-guide.html#connection-and-channel-lifspan) in .NET client docs as well as [Monitoring: High Connection Churn](https://www.rabbitmq.com/connections.html#monitoring) mention that connections in the protocols we support are meant to be long-lived.
